config/routes.rb
Rails.application.routes.draw do
  resources :meals
  resources :customers
  resources :cooks
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cook.rb
# require 'pry'
class Cook < ApplicationRecord
    has_many :meals
    has_many :customers, through: :meals

    validates :age, inclusion: {in: 0..210}
    validate :restrict_name

    def restrict_name
        if !name.include?("beef")
            errors.add(:name, "NO BEEF")
        end
    end
end

app/models/customer.rb
class Customer < ApplicationRecord
    has_many :meals
    has_many :cooks, through: :meals
end

app/models/meal.rb
class Meal < ApplicationRecord
    belongs_to :customer
    belongs_to :cook
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cooks_controller.rb
class CooksController < ApplicationController

    def index
        @cooks = Cook.all
    end

    def new
        @cook = Cook.new
    end

    def create
        @cook = Cook.create(cook_params)
        redirect_to cook_path(@cook)
    end

    def show
        @cook = Cook.find(params[:id])
    end

    def edit
        @cook = Cook.find(params[:id])
    end

    def update
        @cook = Cook.find(params[:id])
        @cook.update(cook_params)
        redirect_to cook_path(@cook)
    end

    private
    def cook_params
        params.require(:cook).permit(:name, :age, :specialty)
    end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
end

app/controllers/meals_controller.rb
class MealsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cooks_helper.rb
module CooksHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/meals_helper.rb
module MealsHelper
end

app/views/cooks/edit.html.erb
<h1>Welcome to Party Hard Cooks.</h1>
<%if @cook.errors %>
<%=@cook.errors.full_messages%>
<%end%>
<%=form_for(@cook) do |f|%>
<%=f.label :name%>
<%=f.text_field :name%>
<%=f.label :specialty%>
<%=f.text_field :specialty%>
<%=f.label :age%>
<%=f.number_field :age%>
<%=f.submit%>
<%end%>

app/views/cooks/index.html.erb
<h1>HELLOOOOOOO cooks</h1>
<%@cooks.each do |cook|%>
<li><%=link_to cook.name, cook_path(cook)%></li>
<%end%>

app/views/cooks/new.html.erb
<h1>Welcome to Party Hard Cooks.</h1>
<%=form_for(@cook) do |f|%>
<%=f.label :name%>
<%=f.text_field :name%>
<%=f.label :specialty%>
<%=f.text_field :specialty%>
<%=f.label :age%>
<%=f.number_field :age%>
<%=f.submit%>
<%end%>

app/views/cooks/show.html.erb
<%=@cook.name%>
<%=@cook.specialty%>
<%=@cook.age%>

<%=link_to "edit", edit_cook_path(@cook)%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chef</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>